[config.wallpaper]
command = "hyprctl"
arguments= ["hyprpaper", "reload", ","]

[config]
version_check = false

# Wezterm
[templates.wezterm]
input_path = "./templates/wezterm.toml"
output_path = "~/.config/wezterm/colors/wezterm-matugen.toml"

# Hyprland
[templates.hyprland]
input_path = "./templates/hyprland.conf"
output_path = "~/.config/hypr/hyprland-matugen.conf"

# Waybar
[templates.waybar]
input_path = "./templates/waybar.css"
output_path = "~/.config/waybar/waybar-matugen.css"

# Rofi
[templates.rofi]
input_path = "./templates/rofi.rasi"
output_path = "~/.config/rofi/rofi-matugen.rasi"

# Dunst
[templates.dunst]
input_path = "./templates/dunst"
output_path = "~/.config/dunst/dunstrc"

# Wlogout
[templates.wlogout]
input_path = "./templates/waybar.css"
output_path = "~/.config/wlogout/wlogout-matugen.css"

# NvChad
[templates.nvchad]
input_path = "./templates/nvchad.lua"
output_path = "~/.config/nvim/lua/themes/nvchad-matugen.lua"

# GTK3
[templates.gtk3]
input_path = "./templates/gtk.css"
output_path = "~/.config/gtk-3.0/colors.css"

# GTK4
[templates.gtk4]
input_path = "./templates/gtk.css"
output_path = "~/.config/gtk-4.0/colors.css"

# Qt5
[templates.qt5]
input_path = "./templates/qt.conf"
output_path = "~/.config/qt5ct/colors/qt5-matugen.conf"

# Qt6
[templates.qt6]
input_path = "./templates/qt.conf"
output_path = "~/.config/qt6ct/colors/qt6-matugen.conf"

