[colors]
background = "{{ colors.background.default.hex }}"
foreground = "{{ colors.on_surface.default.hex }}"
selection_bg = "{{ colors.primary.default.hex }}"
selection_fg = "{{ colors.background.default.hex }}"
ansi = [
  "#181818",
  "{{ colors.error.default.hex }}",
  "{{ colors.primary.default.hex }}",
  "{{ colors.inverse_primary.default.hex }}",
  "{{ colors.primary.default.hex }}",
  "{{ colors.tertiary.default.hex }}",
  "{{ colors.secondary.default.hex }}",
  "#bac2de",
]
brights = [
  "#585b70",
  "#f38ba8",
  "#a6e3a1",
  "#f9e2af",
  "#89b4fa",
  "#f5c2e7",
  "#94e2d5",
  "#a6adc8",
]
cursor_bg = "{{ colors.on_surface.default.hex }}"
cursor_fg = "{{ colors.inverse_on_surface.default.hex }}"
cursor_border = "{{ colors.on_surface.default.hex }}"

[metadata]
name = "WezTerm Matugen"
